# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/medimoz/medimoz-sdk-ios.git'
pod 'MedimozSdk', '~> 1.0'

def common_pods

end

target 'SimpleVideoPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleVideoPlayer
  common_pods
end
